### PR TITLE
fixes messages sent to self appear twice

### LINKED ISSUE #109: Messages sent to self appear twice
**Describe the bug**
Response returns duplicate messages when I send a message to myself. This should not happen because it is 1 transaction

**To Reproduce**
curl 'http://localhost:8080/api/ethereum/ropsten/address/0x92d8f10248c6a3953cc3692a894655ad05d61efb/messages' -H 'Accept: application/json, text/plain, */*' -H 'Referer: http://localhost:4200/' -H 'Origin: http://localhost:4200' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36' --compressed
```

**What version of Mailchain are you using ?**
`dev`

**Expected behavior**
One single message

**Screenshots**
N/A

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by nikosk686**
Closes #109

### CODE REVIEW

**Comment by robdefeo** [comment]
Hi @nikosk686 thanks for looking at this issue, I really like the approach you have taken. I have made a suggested change based on out of order messages. It is not expected but good to cover that off while addressing this issue.

**Comment by robdefeo** [comment]
@nikosk686 we would love to talk to you about how you found out about mailchain, what you thought of the project and the experience of making changes. It would be great to get some feedback. If you are open to that we can setup a call or chat.

**Comment by nikosk686** [comment]
Hi @robdefeo!
Thanks for your kind words.

Regarding your changes I totally agree with the approach of covering the out of order case.
Though I hate the fact that you have to simulate Set's behavior with Map and unnecessary boolean values, it seems to be a very common workaround in Go [[1]](https://stackoverflow.com/questions/34018908/golang-why-dont-we-have-a-set-datastructure) [[2]](https://softwareengineering.stackexchange.com/questions/177428/sets-data-structure-in-golang), considering the lack of native Set structure.
So this is how I would have implemented too, if I have thought about the ordering problem in first place :)
Also it seems that transaction's hash field is the only field needed when checking for equality, but as I am new to ethereum world I wasn't sure and I went with the full check (i.e. all fields) solution. Thanks for fixing that too!

Regarding how I have found about mailchain, If I recall correctly I read about it in a relatively randomly accessed medium post (maybe yours?) which I cannot find right now.
The nice thing about this fact is that when I read this post I was really in the start of my journey both on Golang and ethereum/blockchain.
So mailchain is a great match for my current "learning new skills" endeavors.

Of course I am open for call/chat, but since now is my summer holidays period lets leave this for the end of the month.
However do not hesitate to send me an inbox in the email address of my [Github account](https://github.com/nikosk686) if you have any ideas for mailchain's expansion or any already open issues (both on maicahin or mailchain-web, as I am into angular/typescript too) that you need help.

Nikos

**Comment by robdefeo** [comment]
@nikosk686 appologies for the slow delay responding, I am also on holiday in this period. I'll send you an email in approx one week to set up a chat. 

Sets are missing natively in Go, while `map[type]bool` gives the same functionality with a relatively small amount of code it does lack in readability. If there was an explicit set type the explanation that you intended to use it in this way would form part of readability.
The issue didn't have enough detail regarding test cases or acceptance criteria, that is something we need to work on, do you have an opinion on how you would best like to see that?
The hash is calculated using `keccak256` of the fields, it can be reliably used for a key the mailchain use case and we do use it and intend to use it this way in the future.

Its exciting to hear that you learnt a little about both Ethereum and Golang partly due to Mailchain, we are happy to help you in this. We have lots of exciting plans and can share then with you and we will be writing up a lot more detail.

Have a great holiday! :surfer:

**Pull request merged**
