### PR TITLE
Add Goerli support

### PR DESCRIPTION
**Pull request by tboeckmann**

### CODE REVIEW

**Comment by tboeckmann** [comment]
Should close #152

**Comment by robdefeo** [comment]
Does etherscan support goreli? The API https://api-goreli.etherscan.io/api?module=stats&action=ethsupply&apikey=YourApiKeyToken doesnt give any response.

**Comment by tboeckmann** [comment]
Try this: https://api-goerli.etherscan.io/api?module=proxy&action=eth_blockNumber&apikey=YourApiKeyToken

**Comment by robdefeo** [comment]
Right ok, the change looks good. Need to see if Etherscan supports it in the same way.

**Pull request merged**
