### PR TITLE
feat: docker-compose to create postgres db

### LINKED ISSUE #474: create docker for postgres database
**Is your feature request related to a problem? Please describe.**
running `cmd/indexer` is difficult without configuring a postgres database

**Describe the solution you'd like**
- [ ] docker compose file that brings up a postgres database
- [ ] use `volumes:` to store database

### PR DESCRIPTION
**Pull request by ramkumarvenkat**
Fixes #474

### CODE REVIEW

**Comment by ramkumarvenkat** [comment]
@robdefeo I believe we will run `migrate` on the new run command (which will be created in #473)?

**Comment by ramkumarvenkat** [comment]
Tested it by starting the container, creating the tables, stopping and restarting it.

The volumes persisted made sure the tables are present after restart.

**Comment by robdefeo** [comment]
> @robdefeo 2 questions:
> 
> 1. I believe we will run `migrate` on the new run command (which will be created in #473)?
> 2. Starting the containers will happen in the `serve` command?

@ramkumarvenkat I like your questions 😄 

1. A command should do a single action, although in this case it looks like there is no obvious side effect of `migrate` running with the `run` command it is not clear what is happening when `run` is executed. *Note: I did try something similar in the past to do a `migrate` on `run` in this case there could be more than one instance running and attempting to migrate the database. This caused data consistency problems, we changed the approach to have `migrate` execute as part of deployment and `run` during normal operation *

**Comment by robdefeo** [comment]
> Tested it by starting the container, creating the tables, stopping and restarting it.
> 
> The volumes persisted made sure the tables are present after restart.

Thanks, that is exactly what is needed.

**Pull request merged**
