### PR TITLE
chore: tests - remove references to pk hex in non secp256k1 packages

### LINKED ISSUE #481: remove reference to PK hex bytes from non secp256k1 packages
**Is your feature request related to a problem? Please describe.**
`DF4BA9F6106AD2846472F759476535E55C5805D8337DF5A11C3B139F438B98B3` and `01901E63389EF02EAA7C5782E08B40D98FAEF835F28BD144EECF5614A415943F` should only be used in

**Is your feature request related to a problem? Please describe.**
- [ ] Replace reference to `DF4BA9F6106AD2846472F759476535E55C5805D8337DF5A11C3B139F438B98B3` in all packages except `crypto/secp256k1` and `crypto/secp256k1/secp256k1test`. Change to `CharlottePrivateKey` and use `Bytes()`
- [ ] Replace reference to `01901E63389EF02EAA7C5782E08B40D98FAEF835F28BD144EECF5614A415943F` in all packages except `crypto/secp256k1` and `crypto/secp256k1/secp256k1test`. Change to `SofiaPrivateKey` and use `Bytes()`

### PR DESCRIPTION
**Pull request by ramkumarvenkat**
Fixes #481

### CODE REVIEW

**Comment by ramkumarvenkat** [comment]
@robdefeo Have a couple of questions:
1) SofiaPrivateKey passphrase is still hard-coded inside https://github.com/mailchain/mailchain/blob/master/cmd/mailchain/commands/account_test.go#L165. Will it be a good idea to create these constants inside `secp256k1/keys_test.go` and reference it everywhere?
2) Adding to the above, I believe I can reference the same inside `secp256k1test` as well? I see that there is duplication in `secp256k1test` and `secp256k1` and `secp256k1test` makes it global
3) Also I see that ECDSA keys are created in `ecdsa_test.go`. Does it make sense to unify all the keys (secp 256k1 and ecdsa) in some package and make it global?

**Comment by ramkumarvenkat** [comment]
Thanks @robdefeo , your suggestion worked!! Also thanks for pointing out the reasoning behind the secp256k1 and secp256k1test packages.

In hindsight, I should have poked around a bit to see how to convert the key bytes to the hex string. I will do a bit more poking around from the next time.

**Comment by robdefeo** [comment]
@ramkumarvenkat glad it makes sense to you. I am happy to answer your questions and explain the reasoning. It good to have you ask these sort of questions and challenge the thinking where appropriate. Poke around as much as need but also feel free to ask questions.

**Comment by robdefeo** [comment]
@ramkumarvenkat there appears to be an error on this PR, probably best to update the branch if all the tests passed locally.

**Comment by ramkumarvenkat** [comment]
Thanks @robdefeo , merge from master fixed the tests!

**Pull request merged**
